Repository GSG-G9/Rawdaty, pull requests merged in 2021-02, with the labels that each got.

#27 Initial file structure
  .gitignore
  README.md
  client/.eslintcache
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/controllers/index.js
  server/database/data/index.js
  server/database/queries/index.js
  server/routes/index.js
  server/utils/index.js
  test/index.test.js
Labels: Backend, Frontend

#56 Make sql connection and Create schema
  .vscode/settings.json
  package.json
  server/database/data/build.js
  server/database/data/connection.js
  server/database/data/databaseConfig.sql
  server/database/data/index.js
  server/database/data/rawdaty.sql
  server/database/data/rawdatyFake.sql
Labels: Approved

#62 Rating component
  .vscode/settings.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App/App.css
  client/src/App/App.js
  client/src/Components/Common/Rating/index.js
  client/src/index.js
Labels: Awaiting Review

#60 MainButton Component
  client/src/App/App.js
  client/src/Components/Common/MainButton/index.js
Labels: Awaiting Review

#63 UserImage component
  client/src/Components/Common/UserImage/index.js
  client/src/Components/Common/UserImage/style.css
Labels: Awaiting Review, Priority-1

#61 DropList Component
  client/public/index.html
  client/src/App/index.js
  client/src/App/style.css
  client/src/Components/Common/DropList/index.js
  client/src/Components/Common/DropList/style.css
  client/src/assets/icons/location.svg
  client/src/index.js
Labels: Approved, Priority-1

#66 Card Component
  client/src/App/index.js
  client/src/App/style.css
  client/src/Components/Common/Card/README.md
  client/src/Components/Common/Card/index.js
  client/src/Components/Common/Card/style.css
Labels: Approved, Priority-2

#64 Comment Component
  client/src/Components/Common/Comment/index.js
  client/src/Components/Common/Comment/style.css
  client/src/Components/Common/MainButton/index.js
  client/src/Components/Common/UserImage/style.css
Labels: Awaiting Review, Priority-1

#67 Footer Component
  client/src/App/index.js
  client/src/Components/Layout/Footer/index.js
  client/src/Components/Layout/Footer/style.css
  client/src/assets/icons/facebook.svg
  client/src/assets/icons/instagram.svg
  client/src/assets/icons/twitter.svg
Labels: Done

#72 Comments Container
  client/src/Components/CommentContainer/index.js
Labels: Approved

#71 SideBar Component
  client/.eslintrc.json
  client/src/Components/Layout/SideBar/index.js
  client/src/Components/Layout/SideBar/style.css
Labels: Approved

#68 Navbar Component
  client/src/App/index.js
  client/src/Components/Common/NavTap/index.js
  client/src/Components/Common/NavTap/style.css
  client/src/Components/Layout/Navbar/index.js
  client/src/Components/Layout/Navbar/style.css
  client/src/assets/icons/homedrop.svg
  client/src/assets/icons/logout.svg
Labels: Awaiting Review, Frontend

#69 Search Component
  client/.eslintrc.json
  client/src/App/style.css
  client/src/Components/Common/DropList/index.js
  client/src/Components/Common/MainInput/style.css
  client/src/Components/Search/index.js
  client/src/Components/Search/style.css
  client/src/assets/icons/price.svg
Labels: Awaiting Review

#78 Create Loading Component
  client/package-lock.json
  client/src/Components/Common/Loading/index.js
Labels: Approved

#76 Card Container
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.css
  client/src/Components/Common/Card/index.js
Labels: Approved

#77 Create Fake Data
  server/database/data/databaseConfig.sql
  server/database/data/rawdaty.sql
  server/database/data/rawdatyFake.sql
Labels: Approved, Backend, Priority-1

#81 GET | /kindergarten/:id
  server/app.js
  server/controllers/index.js
  server/controllers/kindergarten/getSpecificKindergarten.js
  server/controllers/kindergarten/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/getKindergartenById.js
  server/database/queries/kindergarten/index.js
  server/index.js
  server/router/index.js
  server/router/kindergarten.js
  server/utils/validation/index.js
  server/utils/validation/kindergartenIdSchema.js
  test/kindergarten.test.js
Labels: Approved

#86 edit get kindergarten by id
  server/database/queries/kindergarten/getKindergartenById.js
  server/database/queries/kindergarten/index.js
  test/kindergarten.test.js
Labels: Awaiting Review

#84 GET | /users
  server/controllers/index.js
  server/controllers/users/getUsers/index.js
  server/controllers/users/index.js
  server/database/queries/index.js
  server/database/queries/users/getUsers/index.js
  server/database/queries/users/index.js
  server/router/index.js
  server/router/user.js
  test/index.test.js
  test/kindergarten.test.js
Labels: Approved, Backend

#89 Get | /locations
  server/controllers/index.js
  server/controllers/locations/getLocations/index.js
  server/controllers/locations/index.js
  server/database/queries/index.js
  server/database/queries/locations/getLocations/index.js
  server/database/queries/locations/index.js
  server/router/index.js
  server/router/location.js
  test/index.test.js
Labels: Approved, Backend

#83 GET | /kindergarten
  package-lock.json
  server/controllers/index.js
  server/controllers/kindergarten/getKindergarten.js
  server/controllers/kindergarten/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/getKindergartenQuery.js
  server/database/queries/kindergarten/index.js
  server/router/index.js
  server/router/kindergarten.js
  test/index.test.js
Labels: Approved, Backend

#90 Edit get garten by id route
  .gitignore
  server/database/queries/kindergarten/getKindergartenById.js
  test/index.test.js
Labels: Approved, Done

#85 Get kindergarten comments
  .gitignore
  server/controllers/comments/getComments.js
  server/controllers/comments/index.js
  server/controllers/index.js
  server/database/queries/comments/getCommentsQuery.js
  server/database/queries/comments/index.js
  server/database/queries/index.js
  server/router/comments.js
  server/router/index.js
  test/index.test.js
Labels: Approved, Backend

#87 Add new Comment
  server/controllers/comments/addComments.js
  server/controllers/comments/index.js
  server/controllers/index.js
  server/database/queries/comments/addCommentsQuery.js
  server/database/queries/comments/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/getKindergartenId.js
  server/database/queries/kindergarten/index.js
  server/router/comments.js
  server/utils/validation/addCommentSchema.js
  server/utils/validation/index.js
  test/index.test.js
Labels: Approved, Backend

#93 16 edit sql query getKindergartenById to get the comments avg and count
  server/database/queries/kindergarten/getKindergartenById.js
  test/index.test.js
Labels: Done

#94 Some edits
  client/src/Components/CommentContainer/index.js
  server/database/data/rawdatyFake.sql
  test/index.test.js
Labels: Awaiting Review

#80 GET | search
  server/controllers/index.js
  server/controllers/kindergarten/index.js
  server/controllers/kindergarten/kindergartenSearch.js
  server/database/queries/index.js
  server/database/queries/kindergarten/getKindergartenSearch.js
  server/database/queries/kindergarten/index.js
  server/router/kindergarten.js
  server/utils/validation/index.js
  server/utils/validation/kindergartenSearchSchema.js
  test/index.test.js
Labels: Approved, Backend

#97 Fix | getKindergartens
  server/database/queries/kindergarten/getKindergartenQuery.js
  test/index.test.js
Labels: Backend

#92 Landing page '/'
  client/src/App/index.js
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.css
  client/src/Components/Common/Card/index.js
  client/src/Components/Common/Loading/index.js
  client/src/Components/Common/Spinner/index.js
  client/src/Components/Layout/Navbar/style.css
  client/src/Pages/HomePage/index.js
  client/src/Pages/HomePage/style.css
  client/src/assets/img/header.png
Labels: Awaiting Review, Frontend

#99 fix getKindergartensQuery
  server/database/queries/kindergarten/getKindergartenQuery.js
Labels: Backend, bug

#91 POST | /locations
  server/controllers/index.js
  server/controllers/locations/index.js
  server/controllers/locations/postLocations/index.js
  server/database/queries/index.js
  server/database/queries/locations/index.js
  server/database/queries/locations/postLocations/index.js
  server/router/location.js
  server/utils/validation/index.js
  server/utils/validation/locationSchema.js
  test/index.test.js
Labels: Awaiting Review, Backend

#102 get | logout
  server/controllers/index.js
  server/controllers/users/index.js
  server/controllers/users/logout.js
  server/router/user.js
Labels: Approved, Backend

#106 Fix heroku build script
  client/package-lock.json
  package.json
Labels: bug

#105 POST /signup
  package-lock.json
  package.json
  server/controllers/index.js
  server/controllers/users/addUsers.js
  server/controllers/users/index.js
  server/database/queries/index.js
  server/database/queries/users/addUsersQuery.js
  server/database/queries/users/checkEmail.js
  server/database/queries/users/index.js
  server/router/user.js
  server/utils/jwt.js
  server/utils/validation/addUserSchema.js
  server/utils/validation/index.js
  test/index.test.js
Labels: Approved, Backend, Done

#101 POST | /login
  .vscode/settings.json
  server/controllers/index.js
  server/controllers/users/index.js
  server/controllers/users/login.js
  server/database/data/rawdatyFake.sql
  server/middleware/authentication/index.js
  server/middleware/authentication/protectedAdmin.js
  server/middleware/authentication/verifyUser.js
  server/router/location.js
  server/router/user.js
  server/utils/validation/loginSchema.js
  test/index.test.js
Labels: Approved, Backend

#113 /getAuthUser
  server/controllers/index.js
  server/controllers/users/getAuthUser.js
  server/controllers/users/getUsers.js
  server/controllers/users/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/getKindergartensByUserId.js
  server/database/queries/kindergarten/index.js
  server/database/queries/users/getUserInfoById.js
  server/database/queries/users/index.js
  server/router/user.js
Labels: Approved, Backend

#114 Edit database schema and fakedata
  client/.eslintrc.json
  server/database/data/rawdaty.sql
  server/database/data/rawdatyFake.sql
  test/index.test.js
Labels: bug

#104 DELETE | /kindergarten/:id
  client/package-lock.json
  server/controllers/index.js
  server/controllers/kindergarten/deleteKindergarten.js
  server/controllers/kindergarten/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/deleteKindergarten.js
  server/database/queries/kindergarten/getKindergartenById.js
  server/database/queries/kindergarten/index.js
  server/router/kindergarten.js
  test/index.test.js
Labels: Awaiting Review

#103 Post| /kindergarten
  server/controllers/index.js
  server/controllers/kindergarten/addKindergarten.js
  server/controllers/kindergarten/index.js
  server/database/queries/index.js
  server/database/queries/kindergarten/addKindergartenQuery.js
  server/database/queries/kindergarten/index.js
  server/router/kindergarten.js
  server/utils/validation/addKindergartenSchema.js
  server/utils/validation/index.js
  test/index.test.js
Labels: Awaiting Review, Backend

#109 About page
  client/src/App/index.js
  client/src/Components/Header/index.js
  client/src/Components/Header/style.css
  client/src/Pages/HomePage/index.js
  client/src/Pages/HomePage/style.css
  client/src/Pages/ِAboutPage/index.js
  client/src/Pages/ِAboutPage/style.css
  client/src/assets/img/about.jpg
Labels: Awaiting Review, Frontend

#111 Login Page
  client/src/App/index.js
  client/src/App/style.css
  client/src/Components/Common/Card/index.js
  client/src/Components/Common/Card/style.css
  client/src/Components/Common/MainButton/index.js
  client/src/Components/Common/MainInput/index.js
  client/src/Components/Common/MainInput/style.css
  client/src/Components/Common/NavTap/index.js
  client/src/Components/Common/NavTap/style.css
  client/src/Components/Layout/Footer/style.css
  client/src/Components/Layout/Navbar/index.js
  client/src/Components/Layout/Navbar/style.css
  client/src/Components/Layout/SideBar/index.js
  client/src/Components/Layout/SideBar/style.css
  client/src/Context/AuthContext.js
  client/src/Context/LogoutContext.js
  client/src/Pages/HomePage/index.js
  client/src/Pages/LoginPage/index.js
  client/src/Pages/LoginPage/style.css
  client/src/assets/img/login&signUp.png
Labels: Awaiting Review, Frontend

#95 Kindergarten profile
  client/package-lock.json
  client/public/favicon.png
  client/public/index.html
  client/src/App/index.js
  client/src/Components/CommentContainer/index.js
  client/src/Components/CommentContainer/style.css
  client/src/Components/Common/Comment/index.js
  client/src/Pages/KindergartenProfilePage/index.js
  client/src/Pages/KindergartenProfilePage/style.css
  client/src/assets/icons/comment.svg
  client/src/assets/icons/location1.svg
  client/src/assets/icons/phone.svg
  client/src/assets/icons/time.svg
  server/database/data/rawdatyFake.sql
  test/index.test.js
Labels: Awaiting Review, Frontend

#98 Search Functionality
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/App/style.css
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.css
  client/src/Components/Common/DropList/index.js
  client/src/Components/Common/DropList/style.css
  client/src/Components/Common/NavTap/index.js
  client/src/Components/Common/NavTap/style.css
  client/src/Components/Layout/Navbar/index.js
  client/src/Components/Layout/Navbar/style.css
  client/src/Components/Search/index.js
  client/src/Components/Search/style.css
  client/src/Pages/SearchPage/index.js
  client/src/Pages/SearchPage/style.css
  client/src/assets/icons/homeDrop.svg
  client/src/utils/createSearchUrl.js
  client/src/utils/usePrevious.js
  client/src/utils/validation/kindergartenSearchSchema.js
Labels: Awaiting Review, Frontend

#110 Signup Page
  client/src/App/index.js
  client/src/Components/CardContainer/index.js
  client/src/Pages/LoginPage/index.js
  client/src/Pages/LoginPage/style.css
  client/src/Pages/Signup/index.js
  client/src/assets/img/signup-photo.png
  server/controllers/users/addUsers.js
Labels: Awaiting Review, Frontend
